Import('variant')

obj = variant['env'].StaticObject("mkrnd.cpp")
variant['env'].Program("mkrnd", [obj])

libs=['cds']
if GetOption('use_flloc'):
    libs.append('flloc')
obj = variant['env'].StaticObject("cdsmapperf.c")
variant['env'].Program("cdsmapperf", [obj], LIBS=libs)

obj = variant['env'].StaticObject("stlmapperf.cpp")
variant['env'].Program("stlmapperf", [obj])
