Import('variant')

import os

artefacts = {}

artefacts['incs'] = [os.path.join("include", "cdscommon.h")]

testmain_src = os.path.join("src", "rttestmain.c")
artefacts['rttestmainobj'] = variant['env'].StaticObject(testmain_src)

Return('artefacts')
