Import('variant')

libs=['cds']
if GetOption('use_flloc'):
    libs.append('libflloc')
obj = variant['env'].StaticObject("cdslistperf.c")
variant['env'].Program("cdslistperf", [obj], LIBS=libs)

obj = variant['env'].StaticObject("stllistperf.cpp")
variant['env'].Program("stllistperf", [obj])
